apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: optimizer
  name: optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optimizer
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: optimizer
    spec:
      containers:
        - image: quay.io/orchestrator/optimizer
          name: optimizer
          env:
            - name: OPTIMIZER_CM_NAME
              value: app-config
            - name: OPTIMIZER_CM_NAMESPACE
              value: optimizer
# LOGGING CONFIGURATION
# Use this command to load log4j2.xml in to ConfigMap: oc -n optimizer create cm log-config --from-file log4j2.xml
# Uncomment the following lines in order to have the container mount your logging configuration
#          volumeMounts:
#            - name: log-config
#              mountPath: /optimizer
#      volumes:
#        - name: log-config
#          configMap:
#            name: log-config
